### ISSUE TITLE
Version 0.8.5 doesn't actually set the mod version to 0.8.5

### ISSUE THREAD

**Issue by j-r** [Marnack/advtrains_livery_tools#3]
...leading to a warning from dlxtrains that asks ``compatible_mod_version()`` for 0.8.5.

**Comment by Marnack** [comment]
Thanks, I appreciate your taking the time to report the issue.  Fortunately in this case the warning can be safely ignored.  However, I'll post a fix in the coming weeks.

**Comment by Marnack** [comment]
Corrected in 0.8.5a
